# This is the configuration file for the LightingControl utility 

General:
  # The name of the application
  AppName: LightingControl Dev
  # Number of seconds to wait before checking the schedules again
  CheckInterval: 4
  DisableAllSwitches: False

Website:
  Enable: True
  HostingIP: 0.0.0.0
  Port: 8083
  PageAutoRefresh: 10

ViewerWebsite:
  # Enable or disable posting to the web viewer app
  Enable: False
  BaseURL: http://127.0.0.1:8000
  APITimeout: 20
  # How often to post the state to the web viewer app (in seconds)
  Frequency: 10

# Use this section to configure your Smart devices used to control the lights
# See this page for more information: https://nickelseyspelloc.github.io/sc-smart-device/
SCSmartDevices:
  AllowDebugLogging: False
  ResponseTimeout: 3
  RetryCount: 1
  RetryDelay: 2
  PingAllowed: True
  SimulationFileFolder: simulation_data
  ShellyWebhooks:
    Enabled: True
    Host: 192.168.86.10
    Port: 8787
    Path: /shelly/webhook
    DefaultWebhooks:
      Inputs:
        - input.toggle_on
        - input.toggle_off
  Devices:
    - Name: Spello Kitchen
      Model: Shelly2PMG3
      ExpectOffline: True
      Simulate: True
      Hostname: 192.168.86.37
      Outputs:
        - Name: Spello Kitchen Patio
          Group: Patio
        - Name: Spello Driveway
          Group: Driveway
    - Name: Spello Main Entry
      Model: Shelly2PMG3
      ExpectOffline: True
      Simulate: True
      Hostname: 192.168.86.38
      Outputs:
        - Name: Spello Living Room
          Group: Living Room
        - Name: Spello Front Door
          Group: Patio
    - Name: Spello Patio
      Model: Shelly2LG3
      ExpectOffline: True
      Simulate: False
      Hostname: 192.168.86.36
      Inputs:
        - Name: Spello Patio Rear Input
          Webhooks: True
        - Name: Spello Patio Front Input
          Webhooks: True
      Outputs:
        - Name: Spello Patio Rear
          Group: Patio
        - Name: Spello Patio Front
          Group: Patio

Location:
  Timezone: Europe/Rome
  Latitude: 42.7500
  Longitude: 12.7000

Schedules:
  - Name: Patio Lights
    Events: 
      - TurnOn: "Dusk-00:30"
        TurnOff: "Dawn-01:00"
        RandomOffset: 8
        DaysOfWeek: All
  - Name: Driveway Lights
    Events: 
      - TurnOn: "Dusk-00:15"
        TurnOff: "23:45"
        RandomOffset: 10
        DaysOfWeek: All
  - Name: Living Room
    Events: 
      - TurnOn: "Dusk-01:30"
        TurnOff: "Dawn-04:00"
        RandomOffset: 10
        DaysOfWeek: All
          
LightingControl:
  - Type: Default
    Schedule: Patio Lights
  - Type: Switch Group
    Target: Patio
    Schedule: Patio Lights
  - Type: Switch Group
    Target: Driveway
    Schedule: Driveway Lights
  - Type: Switch Group
    Target: Living Room
    Schedule: Living Room

InputControls:
  - Type: Switch   
    Target: Spello Patio Rear
    Input: Spello Patio Rear Input
  - Type: Switch   
    Target: Spello Patio Front
    Input: Spello Patio Front Input


Files:
  # The name of the saved state file. This is used to store the state of the device between runs.
  SavedStateFile: system_state.json
  LogfileName: logs/logfile.log
  LogfileMaxLines: 1000
  LogProcessID: True
  LogfileVerbosity: debug
  ConsoleVerbosity: debug
  MaxDaysSwitchChangeHistory: 14


# Enter your settings here if you want to be emailed when there's a critical error 
Email:
  EnableEmail: True
  SubjectPrefix: "[Dev Lighting Control]: "


HeartbeatMonitor:
  Enable: False
  WebsiteURL: https://uptime.betterstack.com/api/v1/heartbeat/VBxnh8s7RgwemUbbszYZwHum
  HeartbeatTimeout: 5